### ISSUE TITLE
Arguments

### ISSUE THREAD

**Issue by martppa** [stumbleapp/react-native-app-utils#3]
Is there a way to pass arguments when you start the app? I have tried setting them in AsyncStorage but the promise from AsyncStorage get stuck in firebase service. Thank you.

**Comment by 8BallBomBom** [comment]
There were plans to pass args to the start function and then place them into a bundle which would be fed back to the main activity on launch. Mostly part of an update we haven't got around to yet.
Any suggestions as to how you'd like that? was thinking probably passing an array.

How are you trying to get the AsyncStorage values?
Are you running promise based functions with firebase?
Might be able to use the **finally** promise method.

**Comment by 8BallBomBom** [comment]
I'm gonna close this for now as you can store and retrieve values for use before the app starts and after the app starts depending on how you are handling your background task/service.

This might be something we handle in the future.
Please refer to the suggestions issue [here](https://github.com/stumbleapp/react-native-app-utils/issues/5) if you'd like to see an implementation.
