### ISSUE TITLE
Android 10 not working

### ISSUE THREAD

**Issue by filipthornton** [stumbleapp/react-native-app-utils#6]
I have tested this package on Android 10 and it doesn't seem to be working...anyone has this problem ?

It is working fine on Android 8.1 but not on Android 10. Do you have any solution ?

**Comment by 8BallBomBom** [comment]
We haven't tested with Android 10 as of yet.
Are you getting any errors? and what functions are you having issues with?

**Comment by filipthornton** [comment]
Actually I have tested again everything. Everything seems to be working fine on Android 8.1 and also Android 10 when the app is in the background ( not killed state).

The problem is when the app is in killed state ( swiped out from Recents) then nothing happens. I am using 
                Utils.acquireWakeLock();
	   	Utils.acquireScreenLock();
	   	Utils.startApp();
exactly in this order in messaging().setBackgroundMessageHandler. So practically it is being used for a video call feature. When a call is initiated by user1 firebase send a notification to user2. When that notification is received we wake the phone, unlock the screen and start the app. In killed state it does not work.

If you have any solution or suggestion please let me know....maybe I am doing something wrong

Best regards

**Comment by 8BallBomBom** [comment]
There is a possibility that we can't do much about it but we will look into solutions.

**Comment by 8BallBomBom** [comment]
Can you check if the background message handler is actually being called after the app has been killed.
Should be able to add in some console printing.
Also what device are you using that has issues?

**Comment by filipthornton** [comment]
Yes the background message handler is working. If the app is killed I do receive in the system tray notifications about new messages, received likes or friend requests. I also receive notifications about a missed call when I cancel the call.

I am using for testing these: Samsung A10 with Android 10, Samsung A20 with Android 10 and Nexus 5 with Android 8.1 . These are used on the emulators. 

On a real device I am using Samsung A6 and Motorola Moto G5s (XT1794).

So in killed state nothing happens but let me detail a little the other situations:

1. if the app is in the background with the screen unlocked: on Android 8.1 the app comes to foreground , but on android 10 it doesn't

2. if the app is in the background with the screen locked:  on android 8.1 it is working well; on android 10 the wakelock is working, but the screenunlock and appstart not.

3. if the app is in the foreground with the screen locked:  it is working great on both android 8 and 10.

So if you have any ideas please let me know....

**Comment by 8BallBomBom** [comment]
Thanks for the extensive testing.
I'm currently working on an update for the screen lock function and will see what can be done about the app start function.
It does seem as if with Android 10 there were changes to prevent app starting from background services, we might be able to work around that and will do some research to find a solution, you can read about the changes [here](https://developer.android.com/guide/components/activities/background-starts).

Are you calling the screen unlock and/or wake lock functions before the app start function as intended?

**Comment by 8BallBomBom** [comment]
I've just pushed a quick update which might fix the issues you've been having with the screen lock mechanism on Android 8+
As for the other issue, we are doing some research and looking to implement a solution soon.

**Comment by 8BallBomBom** [comment]
Closed until further testing.
